import { toTypedSchema } from "@vee-validate/zod";
import { z } from "zod";

export const profileFormSchema = toTypedSchema(
  z.object({
    merchantOperatorId: z.string(),
    operatorCode: z.string(),
    operatorRole: z.string(),
    firstName: z.string(),
    middleName: z.string(),
    fullName: z.string(),
    active: z.boolean(),
    // User
    id: z.string(),
    login: z.string(),
    email: z.string().optional(),
    phone: z.string(),
    nationalId: z.string().optional(),
    activated: z.boolean().optional(),
    langKey: z.string().optional(),
    imageUrl: z.string().optional(),
    verificationKey: z.string().optional(),
    resetKey: z.string().optional(),
    resetDate: z.string().optional(),
    deviceId: z.string().optional(),
    unsuccessfulLoginAttempts: z.number().optional(),
    lockCount: z.number().optional(),
    isUserAccountLocked: z.boolean().optional(),
    lockoutDateTime: z.string().optional(),
    preferredOtpMethod: z.string().optional(),
    isPinSet: z.boolean().optional(),
    currentLoginTime: z.string().optional(),
    lastLoginTime: z.string().optional(),
    forcePinChange: z.boolean().optional(),
    emailVerified: z.boolean().optional(),
    verified: z.boolean().optional(),
    createdBy: z.string().optional(),
    createdDate: z.string().optional(),
    lastModifiedBy: z.string().optional(),
    lastModifiedDate: z.string().optional(),
    isEnrolled: z.boolean().optional(),
    authorities: z.array(z.string()).optional(),

    // Merchant
    merchantId: z.string().optional(),
    businessType: z.string().optional(),
    businessNumber: z.string(),
    businessName: z.string(),
    tradeLicenseNumber: z.string().optional(),
    tradeLicenseIssueDate: z.string().optional(),
    tradeLicenseExpiryDate: z.string().optional(),
    taxPayerIdNumber: z.string().optional(),
    taxPayerIssueDate: z.string().optional(),
    taxPayerExpiryDate: z.string().optional(),
    defaultPaymentReceivingAccountNumber: z.string().optional(),
    shortCode: z.string().optional().nullable(),
    status: z.string(),
    // Branch
    merchantBranchId: z.string(),
    branchName: z.string().optional().nullable(),
    branchCode: z.string().optional().nullable(),
    businessPhoneNumber: z.string().optional().nullable(),
    paymentReceivingAccountNumber: z.string().optional().nullable(),
    city: z.string().optional().nullable(),
    businessEmail: z.string().optional().nullable(),
    postalNumber: z.string().optional().nullable(),
    staticQrData: z.string().optional().nullable(),
  })
);
